server:
  port: 8080

spring:
  application:
    name: rococo-gateway

grpc:
  client:
    GLOBAL:
      max-inbound-message-size: 104857600

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

rococo-front:
  base-uri: 'http://127.0.0.1:3000'

grpc:
  client:
    grpcUserClient:
      address: 'static://localhost:9091'
      negotiationType: PLAINTEXT
    grpcMuseumClient:
      address: 'static://localhost:9094'
      negotiationType: PLAINTEXT
    grpcCountryClient:
      address: 'static://localhost:9093'
      negotiationType: PLAINTEXT
    grpcArtistClient:
      address: 'static://localhost:9095'
      negotiationType: PLAINTEXT
    grpcPaintingClient:
      address: 'static://localhost:9096'
      negotiationType: PLAINTEXT
---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'

rococo-front:
  base-uri: 'http://client.rococo.dc'

grpc:
  client:
    grpcUserClient:
      address: 'static://userdata.rococo.dc:9091'
      negotiationType: PLAINTEXT
    grpcMuseumClient:
      address: 'static://museum.rococo.dc:9094'
      negotiationType: PLAINTEXT
    grpcCountryClient:
      address: 'static://country.rococo.dc:9093'
      negotiationType: PLAINTEXT
    grpcArtistClient:
      address: 'static://artist.rococo.dc:9095'
      negotiationType: PLAINTEXT
    grpcPaintingClient:
      address: 'static://painting.rococo.dc:9096'
      negotiationType: PLAINTEXT
